/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;

/**
 *
 * @author TICLAB4
 */
public class viewBotonesListas extends javax.swing.JFrame {

    /**
     * Creates new form viewBotonesListas
     */
    public viewBotonesListas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelColores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        cboColores = new javax.swing.JComboBox<>();
        cboRojo = new javax.swing.JComboBox<>();
        cboVerde = new javax.swing.JComboBox<>();
        cboAzul = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelColores.setBackground(new java.awt.Color(204, 255, 255));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        cboColores.setBackground(new java.awt.Color(204, 204, 255));
        cboColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona opción", "Rojo", "Verde", "Azul", "Amarillo" }));
        cboColores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboColoresItemStateChanged(evt);
            }
        });
        cboColores.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboColoresPropertyChange(evt);
            }
        });

        cboRojo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        cboRojo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboRojoItemStateChanged(evt);
            }
        });
        cboRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRojoActionPerformed(evt);
            }
        });

        cboVerde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verde", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        cboVerde.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboVerdeItemStateChanged(evt);
            }
        });

        cboAzul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        cboAzul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAzulItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelColoresLayout = new javax.swing.GroupLayout(panelColores);
        panelColores.setLayout(panelColoresLayout);
        panelColoresLayout.setHorizontalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoresLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cboColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelColoresLayout.setVerticalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoresLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboColoresPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboColoresPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboColoresPropertyChange

    private void cboColoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboColoresItemStateChanged
        // TODO add your handling code here:
                       //cambiar el color al panel segun el combon box
        String color = cboColores.getSelectedItem().toString();
        System.out.println("Color " + color);
        
        switch(color.toLowerCase()){
            case "rojo":
                panelColores.setBackground(Color.red);
                break;
                
            case "verde":
                panelColores.setBackground(Color.GREEN);
                break;
                
            case "azul":
                panelColores.setBackground(Color.blue);
                break;
               
            case "amarillo":
                panelColores.setBackground(Color.yellow);
                break; 
            
        }
    }//GEN-LAST:event_cboColoresItemStateChanged

    private void cboRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRojoActionPerformed

    private void cboRojoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRojoItemStateChanged
        // TODO add your handling code here:
        String color = cboRojo.getSelectedItem().toString();
        System.out.println("Color " + color);
        
        switch(color.toLowerCase()){
            case "10":
                panelColores.setBackground(new Color(10, 0, 0));
                break;
                
            case "20":
                panelColores.setBackground(new Color(20, 0, 0));
                break;
                
            case "30":
                panelColores.setBackground(new Color(30, 0, 0));
                break;
               
            case "40":
                panelColores.setBackground(new Color(40, 0, 0));
                break; 
                
            case "50":
                panelColores.setBackground(new Color(50, 0, 0));
                break;
                
            case "60":
                panelColores.setBackground(new Color(60, 0, 0));
                break;
                
            case "70":
                panelColores.setBackground(new Color(70, 0, 0));
                break;
                
            case "80":
                panelColores.setBackground(new Color(80, 0, 0));
                break;
                
            case "90":
                panelColores.setBackground(new Color(90, 0, 0));
                break;
                
            case "100":
                panelColores.setBackground(new Color(100, 0, 0));
                break;
            
        }
    }//GEN-LAST:event_cboRojoItemStateChanged

    private void cboVerdeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboVerdeItemStateChanged
        // TODO add your handling code here:
        String color = cboVerde.getSelectedItem().toString();
        System.out.println("Color " + color);
        
        switch(color.toLowerCase()){
            case "10":
                panelColores.setBackground(new Color(0, 10, 0));
                break;
                
            case "20":
                panelColores.setBackground(new Color(0, 20, 0));
                break;
                
            case "30":
                panelColores.setBackground(new Color(0, 30, 0));
                break;
               
            case "40":
                panelColores.setBackground(new Color(0, 40, 0));
                break; 
                
            case "50":
                panelColores.setBackground(new Color(0, 50, 0));
                break;
                
            case "60":
                panelColores.setBackground(new Color(0, 60, 0));
                break;
                
            case "70":
                panelColores.setBackground(new Color(0, 70, 0));
                break;
                
            case "80":
                panelColores.setBackground(new Color(0, 80, 0));
                break;
                
            case "90":
                panelColores.setBackground(new Color(0, 90, 0));
                break;
                
            case "100":
                panelColores.setBackground(new Color(0, 100, 0));
                break;
            
        }
    }//GEN-LAST:event_cboVerdeItemStateChanged

    private void cboAzulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAzulItemStateChanged
        // TODO add your handling code here:
        String color = cboAzul.getSelectedItem().toString();
        System.out.println("Color " + color);
        
        switch(color.toLowerCase()){
            case "10":
                panelColores.setBackground(new Color(0, 0, 10));
                break;
                
            case "20":
                panelColores.setBackground(new Color(0, 0, 20));
                break;
                
            case "30":
                panelColores.setBackground(new Color(0, 0, 30));
                break;
               
            case "40":
                panelColores.setBackground(new Color(0, 0, 40));
                break; 
                
            case "50":
                panelColores.setBackground(new Color(0, 0, 50));
                break;
                
            case "60":
                panelColores.setBackground(new Color(0, 0, 60));
                break;
                
            case "70":
                panelColores.setBackground(new Color(0, 0, 70));
                break;
                
            case "80":
                panelColores.setBackground(new Color(0, 0, 80));
                break;
                
            case "90":
                panelColores.setBackground(new Color(0, 0, 90));
                break;
                
            case "100":
                panelColores.setBackground(new Color(0, 0, 100));
                break;
            
        }
    }//GEN-LAST:event_cboAzulItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewBotonesListas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboAzul;
    private javax.swing.JComboBox<String> cboColores;
    private javax.swing.JComboBox<String> cboRojo;
    private javax.swing.JComboBox<String> cboVerde;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelColores;
    // End of variables declaration//GEN-END:variables
}
