/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class viewRadioBotones extends javax.swing.JFrame {

    /**
     * Creates new form viewRadioBotones
     */
    public viewRadioBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelColor = new javax.swing.JPanel();
        btnCambiarColor = new javax.swing.JButton();
        optionAzul = new javax.swing.JRadioButton();
        optionVerde = new javax.swing.JRadioButton();
        optionRojo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCambiarColor.setText("Cambiar color");
        btnCambiarColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarColorMouseClicked(evt);
            }
        });

        optionAzul.setBackground(new java.awt.Color(53, 169, 226));
        buttonGroup1.add(optionAzul);
        optionAzul.setForeground(new java.awt.Color(255, 255, 255));
        optionAzul.setText("Azul");

        optionVerde.setBackground(new java.awt.Color(178, 224, 155));
        buttonGroup1.add(optionVerde);
        optionVerde.setForeground(new java.awt.Color(255, 255, 255));
        optionVerde.setText("Verde");

        optionRojo.setBackground(new java.awt.Color(243, 121, 121));
        buttonGroup1.add(optionRojo);
        optionRojo.setForeground(new java.awt.Color(255, 255, 255));
        optionRojo.setText("Rojo");
        optionRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionRojoMouseClicked(evt);
            }
        });
        optionRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionRojoActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cambiando el color de fondo");

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
            .addGroup(panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelColorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelColorLayout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(optionRojo)
                                .addComponent(optionAzul)
                                .addComponent(optionVerde))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnCambiarColor, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelColorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)
                    .addComponent(optionRojo)
                    .addGap(18, 18, 18)
                    .addComponent(optionVerde)
                    .addGap(18, 18, 18)
                    .addComponent(optionAzul)
                    .addGap(18, 18, 18)
                    .addComponent(btnCambiarColor)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionRojoActionPerformed

    private void optionRojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionRojoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_optionRojoMouseClicked

    private void btnCambiarColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarColorMouseClicked
        // TODO add your handling code here:
        if(optionRojo.isSelected()){
            panelColor.setBackground(new Color (255, 86, 86));
        }
        
        if(optionVerde.isSelected()){
            panelColor.setBackground(new Color (183, 232, 188));
        }
        
        if(optionAzul.isSelected()){
            panelColor.setBackground(new Color (120, 178, 245));
        }
    }//GEN-LAST:event_btnCambiarColorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewRadioBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewRadioBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewRadioBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewRadioBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewRadioBotones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarColor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton optionAzul;
    private javax.swing.JRadioButton optionRojo;
    private javax.swing.JRadioButton optionVerde;
    private javax.swing.JPanel panelColor;
    // End of variables declaration//GEN-END:variables
}
